version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
   version: "3.12"
   install:
   - requirements: docs/requirements.txt
